const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  getAppVersion: () => ipcRenderer.invoke('get-version'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  checkNodejs: () => ipcRenderer.invoke('check-nodejs'),
  checkNpm: () => ipcRenderer.invoke('check-npm'),
  getNpmRegistry: () => ipcRenderer.invoke('get-npm-registry'),
  checkOpenCode: () => ipcRenderer.invoke('check-opencode'),
  extractNodejs: () => ipcRenderer.invoke('extract-nodejs'),
  configureNpm: (registry) => ipcRenderer.invoke('configure-npm', registry),
  installOpenCode: () => ipcRenderer.invoke('install-opencode'),
  uninstallOpenCode: () => ipcRenderer.invoke('uninstall-opencode'),
  installOpenCodeVersion: (version) => ipcRenderer.invoke('install-opencode-version', version),
  selectDirectory: () => ipcRenderer.invoke('select-directory'),
  launchTUI: (workDir) => ipcRenderer.invoke('launch-tui', workDir),
  launchWeb: (data) => ipcRenderer.invoke('launch-web', data),
  onInstallProgress: (callback) => ipcRenderer.on('install-progress', (event, data) => callback(data)),
  resetEnvironment: () => ipcRenderer.invoke('reset-environment'),
  generateOpenCodeConfig: (options) => ipcRenderer.invoke('generate-opencode-config', options),
  getOpenCodeConfig: () => ipcRenderer.invoke('get-opencode-config'),
  saveOpenCodeConfig: (config) => ipcRenderer.invoke('save-opencode-config', config),
  saveOpenCodeAuth: (apiKey) => ipcRenderer.invoke('save-opencode-auth', apiKey),
  getOpenCodeAuth: () => ipcRenderer.invoke('get-opencode-auth'),
  showConfirmDialog: (options) => ipcRenderer.invoke('show-confirm-dialog', options),
  getZenModels: () => ipcRenderer.invoke('get-zen-models'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  onConfigChange: (callback) => ipcRenderer.on('opencode-config-changed', () => callback()),
  openConfigDirectory: () => ipcRenderer.invoke('open-config-directory'),
  generateAuthFile: (options) => ipcRenderer.invoke('generate-auth-file', options),
  openAuthDirectory: () => ipcRenderer.invoke('open-auth-directory'),
  installSkill: (installDir, skillUrl, isGlobal) => ipcRenderer.invoke('install-skill', installDir, skillUrl, isGlobal),
  onSkillInstallProgress: (callback) => ipcRenderer.on('skill-install-progress', (event, data) => callback(data)),
  checkSkillUpdate: (installDir) => ipcRenderer.invoke('check-skill-update', installDir),
  upgradeSkill: (installDir) => ipcRenderer.invoke('upgrade-skill', installDir),
  searchSkill: (keyword) => ipcRenderer.invoke('search-skill', keyword),
  analyzeSkills: () => ipcRenderer.invoke('analyze-skills'),
  getGlobalSkillDir: () => ipcRenderer.invoke('get-global-skill-dir'),
  openDirectory: (dirPath) => ipcRenderer.invoke('open-directory', dirPath),
  openGlobalSkillsDirectory: () => ipcRenderer.invoke('open-global-skills-directory'),
  openOpenCodeSkillsDirectory: () => ipcRenderer.invoke('open-opencode-skills-directory')
});
